pub const CAMERA_ROTATE_SPEED: f32 = 1.4;
pub const CAMERA_MOVEMENT_SPEED: f32 = 1.;
pub const CAMERA_SIDEWAYS_SPEED_MULT: f32 = 0.85;
pub const CAMERA_BACKWARDS_SPEED_MULT: f32 = 0.75;

pub const GENERATION_PATTERN_SIZE: usize = 6;
pub const MAX_ROOM_DATA_COUNT: usize = 10_000;
